version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: belajar_typescript
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: belajar_typescript
      DB_PASS: postgres
      DB_PORT: 5432
      PORT: 7086
    ports:
      - "7086:7086"

volumes:
  pgdata:
